filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
      - /var/log/syslog
      - /var/log/auth.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

filebeat.modules:
  - module: nginx
    access:
      enabled: true
    error:
      enabled: true

logging.level: debug
